# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
#paginate: 10                                #分页时每页博文数量

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
theme: minima
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

anchorjs: true 

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Minhuan's Blog
description: 
timezone: Asia/Shanghai
#keywords: 'jekyll,theme,gem-based,blog'
author:
  name: Minhuan
  job_title: 
  location: 
  email: 
  social_links:
home:
  section1: <h1>Simple Makes Perfect</h1>
  #section2: <h2>ask why before the what and how</h2>
  #section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/yizeng/jekyll-theme-simple-texture" title="View on GitHub"></a></div>
blog:
  #cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License
  #cc_license_image: /assets/images/theme/cc-by-sa.png # Choose one at https://creativecommons.org/choose/
  footer_content:  "Make Things that Really Work and Others Want Them"

disqus:
  shortname: 
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
